import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traduções
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Hero
    'hero.subtitle': 'Uma experiência de hospedagem autêntica e acolhedora, onde a tradição cabo-verdiana encontra o conforto moderno.',
    'hero.button': 'Reservar',
    
    // Header
    'nav.about': 'Sobre',
    'nav.rooms': 'Quartos',
    'nav.gallery': 'Galeria',
    'nav.reviews': 'Avaliações',
    'nav.blog': 'Blog',
    'nav.contact': 'Contato',
    'button.book': 'Reservar Agora',
    'button.book.mobile': 'Reservar',
    'button.login': 'Entrar',
    'button.login.mobile': 'Entrar / Criar conta',
    'button.logout': 'Sair',
    'button.myReservations': 'Minhas Reservas',
    
    // Rooms
    'rooms.title': 'Nossos Quartos',
    'rooms.subtitle': 'Acomodações pensadas para seu conforto e bem-estar',
    'rooms.1.name': 'Quarto Dunas',
    'rooms.1.description': 'Quarto acolhedor e elegante, inspirado na tranquilidade do entardecer. Com uma ampla cama de casal, iluminação suave e decoração com tons naturais, é o espaço perfeito para descansar após um dia a explorar Mindelo. Dispõe de casa de banho privativa, roupeiro embutido e ventoinha para o seu conforto. Um verdadeiro refúgio para quem procura serenidade e bem-estar.',
    'rooms.2.name': 'Suite Baía Tranquila',
    'rooms.2.description': 'A Suite Baía Tranquila é um convite ao descanso e à contemplação. Ampla, luminosa e com decoração minimalista, oferece uma varanda privativa com vista deslumbrante da Baía, ideal para relaxar ao pôr do sol. Equipada com cama de casal, ar condicionado, frigobar e banheira, é perfeita para casais que buscam conforto e privacidade em Mindelo.',
    'rooms.3.name': 'Suite Terraço do Sol',
    'rooms.3.description': 'O Suíte Terraço do Sol oferece conforto e espaço com dois quartos conectados, área de estar e uma atmosfera aconchegante. A decoração rústica com tons quentes e detalhes naturais cria uma experiência relaxante e acolhedora. O grande destaque fica por conta do terraço privativo com rede e cadeiras ao ar livre, perfeito para aproveitar o sol, ler um livro ou admirar a vista para o mar ao entardecer.',
    'rooms.4.name': 'Quarto Morabeza',
    'rooms.4.description': 'Amplo quarto duplo com espaço extra para maior conforto e relaxamento. Dispõe de casa de banho privativa, roupeiro embutido e ventoinha para o seu conforto. Um verdadeiro refúgio para quem procura serenidade e bem-estar.',
    'rooms.amenities': 'Comodidades:',
    'rooms.book': 'Reservar',
    'rooms.moreDetails': 'Mais Detalhes',
    'rooms.fromPrice': 'a partir de',
    'rooms.noRoomsForGuests': 'Nenhum quarto disponível para o número de hóspedes selecionado.',
    'rooms.highlight.popular': 'Mais Popular',
    'rooms.highlight.premium': 'Vista Premium',
    'rooms.highlight.seaView': 'Vista Mar',
    'rooms.highlight.moreSpace': 'Mais Espaço',
    'rooms.capacity.person': 'pessoa',
    'rooms.capacity.people': 'pessoas',
    'rooms.period': 'noite',
    // Amenities
    'rooms.amenity.wifi': 'Wi-Fi',
    'rooms.amenity.tv': 'TV',
    'rooms.amenity.minibar': 'Frigobar',
    'rooms.amenity.privateBathroom': 'Banheiro Privativo',
    'rooms.amenity.airConditioning': 'Ar Condicionado (Brevemente)',
    'rooms.amenity.bathtub': 'Banheira',
    'rooms.amenity.balcony': 'Varanda',
    'rooms.amenity.bathroom': '1 Banheiro',
    'rooms.amenity.seaView': 'Vista Mar',
    'rooms.amenity.extraArea': 'Área Extra',
    
    // Hero Booking Form
    'hero.checkAvailability': 'Verificar Disponibilidade',
    
    // About
    'about.title': 'Nossa História',
    'about.subtitle': 'Descubra a paixão e o cuidado por trás de cada detalhe da Casa Tiana',
    'about.story.title': 'Casa Tiana – Um Refúgio com Alma em Mindelo',
    'about.story.main': 'A Casa Tiana é um refúgio de bem-estar no Mindelo, onde o calor humano se une à beleza local, oferecendo uma experiência única. Cada detalhe harmoniza o conforto moderno com a energia vibrante da cidade, onde a cultura pulsa, o sol abraça e o mar inspira tranquilidade. Mais que uma estadia, a Casa Tiana proporciona uma memória afetiva inesquecível.',
    'about.story.p1': 'Nascida do sonho de criar um espaço acolhedor à beira-mar, a Casa Tiana foi fundada com amor, cuidado e propósito.',
    'about.story.p2': 'Somos uma família apaixonada por bem-receber, e nos dedicamos diariamente a oferecer experiências autênticas, encantadoras e inesquecíveis a cada hóspede.',
    'about.story.p3': 'Cada detalhe da casa foi pensado para harmonizar o conforto da vida moderna com o charme vibrante e a energia única de Mindelo — onde a cultura pulsa, o sol abraça e o mar inspira tranquilidade.',
    'about.hosts': 'Família Tiana',
    'about.hosts.subtitle': 'Seus anfitriões',
    'about.sustainability': 'Sustentabilidade',
    'about.sustainability.desc': 'Comprometidos com práticas eco-friendly e preservação do meio ambiente.',
    'about.hospitality': 'Hospitalidade Genuína',
    'about.hospitality.desc': 'Recebemos cada hóspede como família, oferecendo cuidado e atenção personalizada.',
    'about.community': 'Comunidade Local',
    'about.community.desc': 'Valorizamos e apoiamos a cultura e economia da nossa região.',
    
    // Reviews
    'reviews.title': 'O Que Dizem Nossos Hóspedes',
    'reviews.subtitle': 'Experiências reais de pessoas que escolheram a Casa Tiana para momentos especiais',
    'reviews.rating': 'Avaliação Média',
    'reviews.positive': 'Avaliações Positivas',
    'reviews.recommend': 'Recomendariam',
    'reviews.cta.title': 'Seja Nosso Próximo Hóspede Feliz!',
    'reviews.cta.subtitle': 'Junte-se às centenas de pessoas que já viveram experiências únicas na Casa Tiana',
    
    // Gallery
    'gallery.title': 'Galeria de Fotos',
    'gallery.subtitle': 'Descubra a beleza e o charme da Casa Tiana através de imagens',
    
    // Events
    'events.title': 'Eventos e Atividades',
    'events.subtitle': 'Descubra experiências únicas e atividades especiais para tornar sua estadia ainda mais memorável',
    'events.book': 'Reservar',
    'events.bookNow': 'Reservar Agora',
    
    // Contact
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Estamos aqui para ajudar você a planejar sua estadia perfeita na Casa Tiana',
    'contact.form.title': 'Envie sua Mensagem',
    'contact.form.name': 'Nome *',
    'contact.form.namePlaceholder': 'Seu nome completo',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'seu@email.com',
    'contact.form.phone': 'Telefone',
    'contact.form.phonePlaceholder': '(11) 99999-9999',
    'contact.form.subject': 'Assunto',
    'contact.form.subjectPlaceholder': 'Selecione um assunto',
    'contact.form.subjectReservation': 'Reserva',
    'contact.form.subjectInfo': 'Informações Gerais',
    'contact.form.subjectEvents': 'Eventos Especiais',
    'contact.form.subjectSuggestions': 'Sugestões',
    'contact.form.subjectOther': 'Outros',
    'contact.form.message': 'Mensagem *',
    'contact.form.messagePlaceholder': 'Conte-nos como podemos ajudar você...',
    'contact.form.submit': 'Enviar Mensagem',
    'contact.form.submitting': 'A enviar...',
    'contact.form.successTitle': 'Mensagem Enviada!',
    'contact.form.successDescription': 'Obrigado pelo seu contacto. Responderemos em breve.',
    'contact.form.errorTitle': 'Erro',
    'contact.form.errorDescription': 'Por favor, corrija os campos destacados.',
    'contact.form.errorSubmit': 'Não foi possível enviar a mensagem. Tente novamente.',
    'contact.form.errorRequired': 'Este campo é obrigatório',
    'contact.form.errorInvalidEmail': 'Email inválido',
    'contact.form.errorMaxLength': 'Texto muito longo',
    'contact.info.title': 'Informações de Contato',
    'contact.info.address': 'Endereço',
    'contact.info.phone': 'Telefone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Horário de Atendimento',
    'contact.info.hoursWeekday': 'Segunda a Sexta: 8h às 18h',
    'contact.info.hoursWeekend': 'Sábado e Domingo: 8h às 20h',
    'contact.whatsapp': 'Falar no WhatsApp',
    'contact.whatsapp.message': 'Olá! Gostaria de fazer uma reserva na Casa Tiana.',
    'contact.quickHelp': 'Precisa de Ajuda Rápida?',
    'contact.urgent.title': 'Reservas Urgentes',
    'contact.urgent.desc': 'Para reservas de última hora',
    'contact.urgent.button': 'Ligar Agora',
    'contact.support.title': 'Suporte 24h',
    'contact.support.desc': 'Atendimento via WhatsApp',
    'contact.support.button': 'Enviar Mensagem',
    'contact.events.title': 'Eventos Especiais',
    'contact.events.desc': 'Casamentos e celebrações',
    'contact.events.button': 'Solicitar Orçamento',
    
    // Footer
    'footer.description': 'Uma experiência única de hospedagem em harmonia com a natureza. Localizada em Mindelo, oferecemos momentos inesquecíveis em um ambiente aconchegante e acolhedor.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.contact': 'Contato',
    'footer.followUs': 'Siga-nos',
    'footer.languages': 'Idiomas',
    'footer.awards': 'Reconhecimentos',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Uso',
    'footer.cancellation': 'Política de Cancelamento',
    'footer.reviews': 'avaliações',
    
    // Blog (basic)
    'blog.back': 'Voltar ao Blog',
    'blog.category': 'Turismo',
    'blog.author': 'Equipe Casa Tiana',
    'blog.reading': '8 min de leitura',
    'blog.readMore': 'Ler mais',
    
    // 404
    'notfound.title': '404',
    'notfound.subtitle': 'Oops! Página não encontrada',
    'notfound.home': 'Voltar ao Início',
    
    // My Reservations
    'reservations.title': 'Minhas Reservas',
    'reservations.empty': 'Você ainda não possui nenhuma reserva.',
    'reservations.viewRooms': 'Ver Quartos Disponíveis',
    'reservations.number': 'Reserva',
    'reservations.room': 'Quarto',
    'reservations.checkIn': 'Check-in',
    'reservations.checkOut': 'Check-out',
    'reservations.guests': 'Hóspedes',
    'reservations.total': 'Total',
    'reservations.status': 'Status',
    'reservations.actions': 'Ações',
    'reservations.edit': 'Editar',
    'reservations.cancel': 'Cancelar',
    'reservations.status.pending': 'Pendente',
    'reservations.status.confirmed': 'Confirmada',
    'reservations.status.cancelled': 'Cancelada',
    
    // Weather
    'weather.title': 'Clima em Mindelo',
    'weather.now': 'Agora',
    
    // Travel Recommendations
    'travel.title': 'Recomendações de Viagem',
    'travel.subtitle': 'Descubra experiências personalizadas em Mindelo com a ajuda da nossa IA',
    'travel.interests': 'Seus Interesses',
    'travel.interests.culture': 'Cultura & História',
    'travel.interests.nature': 'Natureza & Praias',
    'travel.interests.gastronomy': 'Gastronomia',
    'travel.interests.music': 'Música & Vida Noturna',
    'travel.interests.adventure': 'Aventura & Esportes',
    'travel.duration': 'Duração da Estadia',
    'travel.duration.1-2': '1-2 dias',
    'travel.duration.3-5': '3-5 dias',
    'travel.duration.week': '1 semana+',
    'travel.style': 'Estilo de Viagem',
    'travel.style.relaxed': 'Relaxado',
    'travel.style.balanced': 'Equilibrado',
    'travel.style.intensive': 'Intensivo',
    'travel.generate': 'Gerar Recomendações',
    'travel.generating': 'Gerando...',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.register': 'Criar Conta',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.name': 'Nome Completo',
    'auth.forgotPassword': 'Esqueci minha senha',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.hasAccount': 'Já tem uma conta?',
    'auth.backToSite': 'Voltar para o site',
    'auth.loginSubtitle': 'Entre na sua conta para fazer reservas',
    'auth.registerSubtitle': 'Crie sua conta para começar',
    'auth.loginButton': 'Entrar',
    'auth.registerButton': 'Criar conta',
    'auth.loggingIn': 'Entrando...',
    'auth.registering': 'Criando conta...',
    'auth.invalidEmail': 'Email inválido',
    'auth.passwordMinLength': 'Senha deve ter pelo menos 6 caracteres',
    'auth.loginError': 'Erro ao entrar',
    'auth.invalidCredentials': 'Email ou senha incorretos.',
    'auth.welcome': 'Bem-vindo!',
    'auth.loginSuccess': 'Login realizado com sucesso.',
    'auth.emailRegistered': 'Email já cadastrado',
    'auth.emailRegisteredMessage': 'Este email já está registrado. Tente fazer login.',
    'auth.registerError': 'Erro ao criar conta',
    'auth.accountCreated': 'Verifique seu email!',
    'auth.accountCreatedMessage': 'Enviámos um link de confirmação para o seu email. Por favor, clique no link para ativar a sua conta.',
    'auth.continueWithGoogle': 'Continuar com Google',
    'auth.orContinueWith': 'ou continue com email',
    
    // Booking Modal
    'booking.title': 'Faça sua Reserva',
    'booking.confirmed': 'Reserva Confirmada!',
    'booking.loginRequired': 'Faça login para reservar',
    'booking.loginMessage': 'Para fazer uma reserva, você precisa estar logado na sua conta.',
    'booking.loginButton': 'Entrar na conta',
    'booking.noAccount': 'Não tem conta?',
    'booking.createAccount': 'Criar conta grátis',
    'booking.loginToContinue': 'Faça login para finalizar a reserva',
    'booking.loginToContinueDescription': 'Os seus dados de reserva serão mantidos após o login.',
    'booking.step1Title': 'Selecione as datas e número de hóspedes',
    'booking.checkIn': 'Check-in',
    'booking.checkOut': 'Check-out',
    'booking.selectCheckIn': 'Selecione check-in',
    'booking.selectCheckOut': 'Selecione check-out',
    'booking.guests': 'Número de hóspedes',
    'booking.person': 'pessoa',
    'booking.people': 'pessoas',
    'booking.next': 'Próximo',
    'booking.back': 'Voltar',
    'booking.step2Title': 'Escolha seu quarto',
    'booking.perNight': 'por noite',
    'booking.summary': 'Resumo da Reserva',
    'booking.period': 'Período',
    'booking.night': 'noite',
    'booking.nights': 'noites',
    'booking.collapse': 'Minimizar',
    'booking.total': 'Total',
    'booking.step3Title': 'Informações do hóspede',
    'booking.fullName': 'Nome completo *',
    'booking.fullNamePlaceholder': 'Seu nome completo',
    'booking.email': 'Email *',
    'booking.emailPlaceholder': 'seu@email.com',
    'booking.phone': 'Telefone *',
    'booking.phonePlaceholder': '(11) 99999-9999',
    'booking.specialRequests': 'Solicitações especiais',
    'booking.specialRequestsPlaceholder': 'Alguma solicitação especial? (opcional)',
    'booking.finalSummary': 'Resumo Final',
    'booking.room': 'Quarto',
    'booking.processing': 'Processando...',
    'booking.confirm': 'Confirmar Reserva',
    'booking.confirmationTitle': 'Reserva Confirmada!',
    'booking.confirmationMessage': 'Sua reserva foi processada com sucesso. Você receberá um email de confirmação em breve.',
    'booking.reservationNumber': 'Número da Reserva',
    'booking.keepNumber': 'Mantenha este número para futuras consultas',
    'booking.confirmationSentTo': 'Confirmação enviada para',
    'booking.checkInAfter': 'após 14h',
    'booking.checkOutBefore': 'até 12h',
    'booking.errorSelectRoom': 'Por favor, selecione um quarto.',
    'booking.errorTitle': 'Erro',
    'booking.reservationConfirmed': 'Reserva Confirmada!',
    'booking.reservationConfirmedMessage': 'Email de confirmação enviado.',
    'booking.reservationError': 'Erro ao criar reserva',
    'booking.reservationErrorMessage': 'Por favor, tente novamente mais tarde.',
    'booking.dateConflict': 'As datas selecionadas incluem dias indisponíveis. Por favor, escolha outras datas.',
    'booking.reservationCreated': 'Reserva criada! Escolha como deseja pagar.',
    'booking.choosePayment': 'Escolha como deseja pagar',
    'booking.payNow': 'Pagar Agora',
    'booking.payLater': 'Pagar Depois',
    'booking.paymentSecure': 'Pagamento seguro processado por SISP',
    'booking.errorSelectDates': 'Selecione as datas de check-in e check-out',
    'booking.errorFillFields': 'Preencha todos os campos obrigatórios',
    
    // WhatsApp Floating
    'whatsapp.floating.tooltip': 'Precisa de ajuda? Fale connosco!',
    'whatsapp.floating.message': 'Olá! Tenho uma pergunta sobre a Casa Tiana...',
    
    // Blog
    'blog.title': 'Blog & Dicas de Viagem',
    'blog.subtitle': 'Descubra os segredos da região, eventos locais e dicas exclusivas para sua estadia',
    'blog.connectingWP': 'Conectando com WordPress... Mostrando conteúdo local.',
    'blog.newsletter.title': 'Receba Nossas Dicas por Email',
    'blog.newsletter.subtitle': 'Inscreva-se em nossa newsletter e seja o primeiro a saber sobre novos roteiros, eventos especiais e ofertas exclusivas para hóspedes da Casa Tiana.',
    'blog.newsletter.placeholder': 'Seu melhor email',
    'blog.newsletter.button': 'Inscrever-se',
    'blog.newsletter.disclaimer': 'Prometemos não enviar spam. Você pode cancelar a qualquer momento.',
    
    // Events/WordPress Events
    'events.difficulty.easy': 'Fácil',
    'events.difficulty.medium': 'Médio',
    'events.difficulty.hard': 'Difícil',
    'events.at': 'às',
    'events.maxParticipants': 'Máx. {0} participantes',
    'events.includes': 'Inclui:',
    'events.moreItems': '+{0} outros itens',
    'events.bookFor': 'Reservar - €{0}',
    'events.tripAdvisor': 'Mais de 150 avaliações 5 estrelas • 📍 TripAdvisor Travellers\' Choice 2023',
  },
  en: {
    // Hero
    'hero.subtitle': 'An authentic and welcoming hospitality experience, where Cape Verdean tradition meets modern comfort.',
    'hero.button': 'Book Now',
    
    // Header
    'nav.about': 'About',
    'nav.rooms': 'Rooms',
    'nav.gallery': 'Gallery',
    'nav.reviews': 'Reviews',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'button.book': 'Book Now',
    'button.book.mobile': 'Book',
    'button.login': 'Sign In',
    'button.login.mobile': 'Sign In / Register',
    'button.logout': 'Sign Out',
    'button.myReservations': 'My Reservations',
    
    // Rooms
    'rooms.title': 'Our Rooms',
    'rooms.subtitle': 'Accommodations designed for your comfort and well-being',
    'rooms.1.name': 'Dunas Room',
    'rooms.1.description': 'A cozy and elegant room inspired by the tranquility of sunset. With a spacious double bed, soft lighting, and natural-toned décor, it is the perfect space to rest after a day exploring Mindelo. Features a private bathroom, built-in wardrobe, and fan for your comfort. A true retreat for those seeking serenity and well-being.',
    'rooms.2.name': 'Baía Tranquila Suite',
    'rooms.2.description': 'The Baía Tranquila Suite is an invitation to rest and contemplation. Spacious, bright, and with minimalist décor, it offers a private balcony with stunning views of the Bay, ideal for relaxing at sunset. Equipped with a double bed, air conditioning, minibar, and bathtub, it is perfect for couples seeking comfort and privacy in Mindelo.',
    'rooms.3.name': 'Sun Terrace Suite',
    'rooms.3.description': 'The Sun Terrace Suite offers comfort and space with two connected bedrooms, a seating area, and a cozy atmosphere. The rustic décor with warm tones and natural details creates a relaxing and welcoming experience. The highlight is the private terrace with a hammock and outdoor chairs, perfect for enjoying the sun, reading a book, or admiring the sea view at sunset.',
    'rooms.4.name': 'Morabeza Room',
    'rooms.4.description': 'Spacious double room with extra space for greater comfort and relaxation. Features a private bathroom, built-in wardrobe, and fan for your comfort. A true retreat for those seeking serenity and well-being.',
    'rooms.amenities': 'Amenities:',
    'rooms.book': 'Book',
    'rooms.moreDetails': 'More Details',
    'rooms.fromPrice': 'from',
    'rooms.noRoomsForGuests': 'No rooms available for the selected number of guests.',
    'rooms.highlight.popular': 'Most Popular',
    'rooms.highlight.premium': 'Premium View',
    'rooms.highlight.seaView': 'Sea View',
    'rooms.highlight.moreSpace': 'More Space',
    'rooms.capacity.person': 'person',
    'rooms.capacity.people': 'people',
    'rooms.period': 'night',
    // Hero Booking Form
    'hero.checkAvailability': 'Check Availability',
    // Amenities
    'rooms.amenity.wifi': 'Wi-Fi',
    'rooms.amenity.tv': 'TV',
    'rooms.amenity.minibar': 'Minibar',
    'rooms.amenity.privateBathroom': 'Private Bathroom',
    'rooms.amenity.airConditioning': 'Air Conditioning (Coming Soon)',
    'rooms.amenity.bathtub': 'Bathtub',
    'rooms.amenity.balcony': 'Balcony',
    'rooms.amenity.bathroom': '1 Bathroom',
    'rooms.amenity.seaView': 'Sea View',
    'rooms.amenity.extraArea': 'Extra Area',
    
    // About
    'about.title': 'Our Story',
    'about.subtitle': 'Discover the passion and care behind every detail of Casa Tiana',
    'about.story.title': 'Casa Tiana – A Soulful Retreat in Mindelo',
    'about.story.main': 'Casa Tiana is a haven of well-being in Mindelo, where human warmth meets local beauty, offering a unique experience. Every detail harmonizes modern comfort with the vibrant energy of the city, where culture pulses, the sun embraces, and the sea inspires tranquility. More than a stay, Casa Tiana provides an unforgettable emotional memory.',
    'about.story.p1': 'Born from the dream of creating a welcoming seaside space, Casa Tiana was founded with love, care, and purpose.',
    'about.story.p2': 'We are a family passionate about hospitality, and we dedicate ourselves daily to offering authentic, enchanting, and unforgettable experiences to each guest.',
    'about.story.p3': 'Every detail of the house was designed to harmonize the comfort of modern life with the vibrant charm and unique energy of Mindelo — where culture pulses, the sun embraces, and the sea inspires tranquility.',
    'about.hosts': 'Tiana Family',
    'about.hosts.subtitle': 'Your hosts',
    'about.sustainability': 'Sustainability',
    'about.sustainability.desc': 'Committed to eco-friendly practices and environmental preservation.',
    'about.hospitality': 'Genuine Hospitality',
    'about.hospitality.desc': 'We welcome each guest as family, offering personalized care and attention.',
    'about.community': 'Local Community',
    'about.community.desc': 'We value and support the culture and economy of our region.',
    
    // Reviews
    'reviews.title': 'What Our Guests Say',
    'reviews.subtitle': 'Real experiences from people who chose Casa Tiana for special moments',
    'reviews.rating': 'Average Rating',
    'reviews.positive': 'Positive Reviews',
    'reviews.recommend': 'Would Recommend',
    'reviews.cta.title': 'Be Our Next Happy Guest!',
    'reviews.cta.subtitle': 'Join hundreds of people who have already lived unique experiences at Casa Tiana',
    
    // Gallery
    'gallery.title': 'Photo Gallery',
    'gallery.subtitle': 'Discover the beauty and charm of Casa Tiana through images',
    
    // Events
    'events.title': 'Events & Activities',
    'events.subtitle': 'Discover unique experiences and special activities to make your stay even more memorable',
    'events.book': 'Book',
    'events.bookNow': 'Book Now',
    
    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'We are here to help you plan your perfect stay at Casa Tiana',
    'contact.form.title': 'Send Your Message',
    'contact.form.name': 'Name *',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+1 (555) 000-0000',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'Select a subject',
    'contact.form.subjectReservation': 'Reservation',
    'contact.form.subjectInfo': 'General Information',
    'contact.form.subjectEvents': 'Special Events',
    'contact.form.subjectSuggestions': 'Suggestions',
    'contact.form.subjectOther': 'Other',
    'contact.form.message': 'Message *',
    'contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.successTitle': 'Message Sent!',
    'contact.form.successDescription': 'Thank you for contacting us. We will reply soon.',
    'contact.form.errorTitle': 'Error',
    'contact.form.errorDescription': 'Please fix the highlighted fields.',
    'contact.form.errorSubmit': 'Could not send message. Please try again.',
    'contact.form.errorRequired': 'This field is required',
    'contact.form.errorInvalidEmail': 'Invalid email',
    'contact.form.errorMaxLength': 'Text too long',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursWeekday': 'Monday to Friday: 8am to 6pm',
    'contact.info.hoursWeekend': 'Saturday and Sunday: 8am to 8pm',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.whatsapp.message': 'Hello! I would like to make a reservation at Casa Tiana.',
    'contact.quickHelp': 'Need Quick Help?',
    'contact.urgent.title': 'Urgent Bookings',
    'contact.urgent.desc': 'For last-minute reservations',
    'contact.urgent.button': 'Call Now',
    'contact.support.title': '24h Support',
    'contact.support.desc': 'WhatsApp support',
    'contact.support.button': 'Send Message',
    'contact.events.title': 'Special Events',
    'contact.events.desc': 'Weddings and celebrations',
    'contact.events.button': 'Request Quote',
    
    // Footer
    'footer.description': 'A unique accommodation experience in harmony with nature. Located in Mindelo, we offer unforgettable moments in a cozy and welcoming environment.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.languages': 'Languages',
    'footer.awards': 'Awards',
    'footer.copyright': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cancellation': 'Cancellation Policy',
    'footer.reviews': 'reviews',
    
    // Blog (basic)
    'blog.back': 'Back to Blog',
    'blog.category': 'Tourism',
    'blog.author': 'Casa Tiana Team',
    'blog.reading': '8 min read',
    'blog.readMore': 'Read more',
    
    // 404
    'notfound.title': '404',
    'notfound.subtitle': 'Oops! Page not found',
    'notfound.home': 'Return to Home',
    
    // My Reservations
    'reservations.title': 'My Reservations',
    'reservations.empty': 'You don\'t have any reservations yet.',
    'reservations.viewRooms': 'View Available Rooms',
    'reservations.number': 'Reservation',
    'reservations.room': 'Room',
    'reservations.checkIn': 'Check-in',
    'reservations.checkOut': 'Check-out',
    'reservations.guests': 'Guests',
    'reservations.total': 'Total',
    'reservations.status': 'Status',
    'reservations.actions': 'Actions',
    'reservations.edit': 'Edit',
    'reservations.cancel': 'Cancel',
    'reservations.status.pending': 'Pending',
    'reservations.status.confirmed': 'Confirmed',
    'reservations.status.cancelled': 'Cancelled',
    

    // Weather
    'weather.title': 'Weather in Mindelo',
    'weather.now': 'Now',
    
    // Travel Recommendations
    'travel.title': 'Travel Recommendations',
    'travel.subtitle': 'Discover personalized experiences in Mindelo with help from our AI',
    'travel.interests': 'Your Interests',
    'travel.interests.culture': 'Culture & History',
    'travel.interests.nature': 'Nature & Beaches',
    'travel.interests.gastronomy': 'Gastronomy',
    'travel.interests.music': 'Music & Nightlife',
    'travel.interests.adventure': 'Adventure & Sports',
    'travel.duration': 'Length of Stay',
    'travel.duration.1-2': '1-2 days',
    'travel.duration.3-5': '3-5 days',
    'travel.duration.week': '1 week+',
    'travel.style': 'Travel Style',
    'travel.style.relaxed': 'Relaxed',
    'travel.style.balanced': 'Balanced',
    'travel.style.intensive': 'Intensive',
    'travel.generate': 'Generate Recommendations',
    'travel.generating': 'Generating...',
    
    // Auth
    'auth.login': 'Sign In',
    'auth.register': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot my password',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.backToSite': 'Back to site',
    'auth.loginSubtitle': 'Sign in to your account to make reservations',
    'auth.registerSubtitle': 'Create your account to get started',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Create Account',
    'auth.loggingIn': 'Signing in...',
    'auth.registering': 'Creating account...',
    'auth.invalidEmail': 'Invalid email',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.loginError': 'Login error',
    'auth.invalidCredentials': 'Incorrect email or password.',
    'auth.welcome': 'Welcome!',
    'auth.loginSuccess': 'Login successful.',
    'auth.emailRegistered': 'Email already registered',
    'auth.emailRegisteredMessage': 'This email is already registered. Try logging in.',
    'auth.registerError': 'Registration error',
    'auth.accountCreated': 'Check your email!',
    'auth.accountCreatedMessage': 'We sent a confirmation link to your email. Please click the link to activate your account.',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.orContinueWith': 'or continue with email',
    
    // Booking Modal
    'booking.title': 'Make Your Reservation',
    'booking.confirmed': 'Reservation Confirmed!',
    'booking.loginRequired': 'Login to book',
    'booking.loginMessage': 'To make a reservation, you need to be logged into your account.',
    'booking.loginButton': 'Sign in',
    'booking.noAccount': 'Don\'t have an account?',
    'booking.createAccount': 'Create free account',
    'booking.loginToContinue': 'Sign in to complete your booking',
    'booking.loginToContinueDescription': 'Your booking details will be saved after login.',
    'booking.step1Title': 'Select dates and number of guests',
    'booking.checkIn': 'Check-in',
    'booking.checkOut': 'Check-out',
    'booking.selectCheckIn': 'Select check-in',
    'booking.selectCheckOut': 'Select check-out',
    'booking.guests': 'Number of guests',
    'booking.person': 'person',
    'booking.people': 'people',
    'booking.next': 'Next',
    'booking.back': 'Back',
    'booking.step2Title': 'Choose your room',
    'booking.perNight': 'per night',
    'booking.summary': 'Booking Summary',
    'booking.period': 'Period',
    'booking.night': 'night',
    'booking.nights': 'nights',
    'booking.collapse': 'Minimize',
    'booking.total': 'Total',
    'booking.step3Title': 'Guest information',
    'booking.fullName': 'Full name *',
    'booking.fullNamePlaceholder': 'Your full name',
    'booking.email': 'Email *',
    'booking.emailPlaceholder': 'your@email.com',
    'booking.phone': 'Phone *',
    'booking.phonePlaceholder': '+1 (555) 000-0000',
    'booking.specialRequests': 'Special requests',
    'booking.specialRequestsPlaceholder': 'Any special requests? (optional)',
    'booking.finalSummary': 'Final Summary',
    'booking.room': 'Room',
    'booking.processing': 'Processing...',
    'booking.confirm': 'Confirm Reservation',
    'booking.confirmationTitle': 'Reservation Confirmed!',
    'booking.confirmationMessage': 'Your reservation has been processed successfully. You will receive a confirmation email shortly.',
    'booking.reservationNumber': 'Reservation Number',
    'booking.keepNumber': 'Keep this number for future reference',
    'booking.confirmationSentTo': 'Confirmation sent to',
    'booking.checkInAfter': 'after 2pm',
    'booking.checkOutBefore': 'by 12pm',
    'booking.errorSelectRoom': 'Please select a room.',
    'booking.errorTitle': 'Error',
    'booking.reservationConfirmed': 'Reservation Confirmed!',
    'booking.reservationConfirmedMessage': 'Confirmation email sent.',
    'booking.reservationError': 'Error creating reservation',
    'booking.reservationErrorMessage': 'Please try again later.',
    'booking.dateConflict': 'The selected dates include unavailable days. Please choose different dates.',
    'booking.reservationCreated': 'Reservation created! Choose how you want to pay.',
    'booking.choosePayment': 'Choose how you want to pay',
    'booking.payNow': 'Pay Now',
    'booking.payLater': 'Pay Later',
    'booking.paymentSecure': 'Secure payment processed by SISP',
    'booking.errorSelectDates': 'Select check-in and check-out dates',
    'booking.errorFillFields': 'Fill in all required fields',
    
    // WhatsApp Floating
    'whatsapp.floating.tooltip': 'Need help? Talk to us!',
    'whatsapp.floating.message': 'Hello! I have a question about Casa Tiana...',
    
    // Blog
    'blog.title': 'Blog & Travel Tips',
    'blog.subtitle': 'Discover local secrets, events and exclusive tips for your stay',
    'blog.connectingWP': 'Connecting to WordPress... Showing local content.',
    'blog.newsletter.title': 'Get Our Tips by Email',
    'blog.newsletter.subtitle': 'Subscribe to our newsletter and be the first to know about new itineraries, special events and exclusive offers for Casa Tiana guests.',
    'blog.newsletter.placeholder': 'Your best email',
    'blog.newsletter.button': 'Subscribe',
    'blog.newsletter.disclaimer': 'We promise not to send spam. You can unsubscribe at any time.',
    
    // Events/WordPress Events
    'events.difficulty.easy': 'Easy',
    'events.difficulty.medium': 'Medium',
    'events.difficulty.hard': 'Hard',
    'events.at': 'at',
    'events.maxParticipants': 'Max. {0} participants',
    'events.includes': 'Includes:',
    'events.moreItems': '+{0} more items',
    'events.bookFor': 'Book - €{0}',
    'events.tripAdvisor': 'Over 150 five-star reviews • 📍 TripAdvisor Travellers\' Choice 2023',
  },
  fr: {
    // Hero
    'hero.subtitle': 'Une expérience d\'hébergement authentique et chaleureuse, où la tradition cap-verdienne rencontre le confort moderne.',
    'hero.button': 'Réserver',
    
    // Header
    'nav.about': 'À propos',
    'nav.rooms': 'Chambres',
    'nav.gallery': 'Galerie',
    'nav.reviews': 'Avis',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'button.book': 'Réserver',
    'button.book.mobile': 'Réserver',
    'button.login': 'Connexion',
    'button.login.mobile': 'Connexion / Inscription',
    'button.logout': 'Déconnexion',
    'button.myReservations': 'Mes Réservations',
    
    // Rooms
    'rooms.title': 'Nos Chambres',
    'rooms.subtitle': 'Hébergements conçus pour votre confort et votre bien-être',
    'rooms.1.name': 'Chambre Dunas',
    'rooms.1.description': 'Une chambre chaleureuse et élégante, inspirée par la tranquillité du crépuscule. Avec un grand lit double, un éclairage doux et une décoration aux tons naturels, c\'est l\'espace parfait pour se reposer après une journée à explorer Mindelo. Dispose d\'une salle de bain privée, d\'une armoire intégrée et d\'un ventilateur pour votre confort. Un véritable refuge pour ceux qui recherchent sérénité et bien-être.',
    'rooms.2.name': 'Suite Baía Tranquila',
    'rooms.2.description': 'La Suite Baía Tranquila est une invitation au repos et à la contemplation. Spacieuse, lumineuse et au décor minimaliste, elle offre un balcon privé avec une vue imprenable sur la Baie, idéale pour se détendre au coucher du soleil. Équipée d\'un lit double, de la climatisation, d\'un minibar et d\'une baignoire, elle est parfaite pour les couples en quête de confort et d\'intimité à Mindelo.',
    'rooms.3.name': 'Suite Terrasse du Soleil',
    'rooms.3.description': 'La Suite Terrasse du Soleil offre confort et espace avec deux chambres communicantes, un coin salon et une atmosphère chaleureuse. La décoration rustique aux tons chauds et aux détails naturels crée une expérience relaxante et accueillante. Le point fort est la terrasse privée avec hamac et chaises en plein air, parfaite pour profiter du soleil, lire un livre ou admirer la vue sur la mer au coucher du soleil.',
    'rooms.4.name': 'Chambre Morabeza',
    'rooms.4.description': 'Grande chambre double avec espace supplémentaire pour plus de confort et de détente. Dispose d\'une salle de bain privée, d\'une armoire intégrée et d\'un ventilateur. Un véritable refuge pour ceux qui recherchent sérénité et bien-être.',
    'rooms.amenities': 'Équipements :',
    'rooms.book': 'Réserver',
    'rooms.highlight.popular': 'Plus Populaire',
    'rooms.highlight.premium': 'Vue Premium',
    'rooms.highlight.seaView': 'Vue Mer',
    'rooms.highlight.moreSpace': 'Plus d\'Espace',
    'rooms.capacity.person': 'personne',
    'rooms.capacity.people': 'personnes',
    'rooms.period': 'nuit',
    // Amenities
    'rooms.amenity.wifi': 'Wi-Fi',
    'rooms.amenity.tv': 'TV',
    'rooms.amenity.minibar': 'Minibar',
    'rooms.amenity.privateBathroom': 'Salle de Bain Privée',
    'rooms.amenity.airConditioning': 'Climatisation (Bientôt)',
    'rooms.amenity.bathtub': 'Baignoire',
    'rooms.amenity.balcony': 'Balcon',
    'rooms.amenity.bathroom': '1 Salle de Bain',
    'rooms.amenity.seaView': 'Vue Mer',
    'rooms.amenity.extraArea': 'Espace Supplémentaire',
    
    // About
    'about.title': 'Notre Histoire',
    'about.subtitle': 'Découvrez la passion et le soin apporté à chaque détail de Casa Tiana',
    'about.story.title': 'Casa Tiana – Un Refuge avec Âme à Mindelo',
    'about.story.main': 'Casa Tiana est un havre de bien-être à Mindelo, où la chaleur humaine rencontre la beauté locale, offrant une expérience unique. Chaque détail harmonise le confort moderne avec l\'énergie vibrante de la ville, où la culture pulse, le soleil embrasse et la mer inspire la tranquillité. Plus qu\'un séjour, Casa Tiana procure un souvenir émotionnel inoubliable.',
    'about.story.p1': 'Née du rêve de créer un espace accueillant en bord de mer, Casa Tiana a été fondée avec amour, soin et détermination.',
    'about.story.p2': 'Nous sommes une famille passionnée par l\'hospitalité, et nous nous consacrons chaque jour à offrir des expériences authentiques, enchanteresses et inoubliables à chaque hôte.',
    'about.story.p3': 'Chaque détail de la maison a été conçu pour harmoniser le confort de la vie moderne avec le charme vibrant et l\'énergie unique de Mindelo — où la culture pulse, le soleil embrasse et la mer inspire la tranquillité.',
    'about.hosts': 'Famille Tiana',
    'about.hosts.subtitle': 'Vos hôtes',
    'about.sustainability': 'Durabilité',
    'about.sustainability.desc': 'Engagés dans des pratiques écologiques et la préservation de l\'environnement.',
    'about.hospitality': 'Hospitalité Authentique',
    'about.hospitality.desc': 'Nous accueillons chaque hôte comme un membre de la famille, avec soin et attention personnalisés.',
    'about.community': 'Communauté Locale',
    'about.community.desc': 'Nous valorisons et soutenons la culture et l\'économie de notre région.',
    
    // Reviews
    'reviews.title': 'Ce Que Disent Nos Hôtes',
    'reviews.subtitle': 'Expériences réelles de personnes qui ont choisi Casa Tiana pour des moments spéciaux',
    'reviews.rating': 'Note Moyenne',
    'reviews.positive': 'Avis Positifs',
    'reviews.recommend': 'Recommanderaient',
    'reviews.cta.title': 'Soyez Notre Prochain Hôte Heureux !',
    'reviews.cta.subtitle': 'Rejoignez les centaines de personnes qui ont déjà vécu des expériences uniques à Casa Tiana',
    
    // Gallery
    'gallery.title': 'Galerie Photos',
    'gallery.subtitle': 'Découvrez la beauté et le charme de Casa Tiana en images',
    
    // Events
    'events.title': 'Événements & Activités',
    'events.subtitle': 'Découvrez des expériences uniques et des activités spéciales pour rendre votre séjour encore plus mémorable',
    'events.book': 'Réserver',
    'events.bookNow': 'Réserver Maintenant',
    
    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.subtitle': 'Nous sommes là pour vous aider à planifier votre séjour parfait à Casa Tiana',
    'contact.form.title': 'Envoyez Votre Message',
    'contact.form.name': 'Nom *',
    'contact.form.namePlaceholder': 'Votre nom complet',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.phone': 'Téléphone',
    'contact.form.phonePlaceholder': '+33 1 23 45 67 89',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'Sélectionnez un sujet',
    'contact.form.subjectReservation': 'Réservation',
    'contact.form.subjectInfo': 'Informations Générales',
    'contact.form.subjectEvents': 'Événements Spéciaux',
    'contact.form.subjectSuggestions': 'Suggestions',
    'contact.form.subjectOther': 'Autre',
    'contact.form.message': 'Message *',
    'contact.form.messagePlaceholder': 'Dites-nous comment nous pouvons vous aider...',
    'contact.form.submit': 'Envoyer le Message',
    'contact.form.submitting': 'Envoi en cours...',
    'contact.form.successTitle': 'Message Envoyé !',
    'contact.form.successDescription': 'Merci de nous avoir contactés. Nous répondrons bientôt.',
    'contact.form.errorTitle': 'Erreur',
    'contact.form.errorDescription': 'Veuillez corriger les champs en surbrillance.',
    'contact.form.errorSubmit': 'Impossible d\'envoyer le message. Veuillez réessayer.',
    'contact.form.errorRequired': 'Ce champ est obligatoire',
    'contact.form.errorInvalidEmail': 'Email invalide',
    'contact.form.errorMaxLength': 'Texte trop long',
    'contact.info.title': 'Informations de Contact',
    'contact.info.address': 'Adresse',
    'contact.info.phone': 'Téléphone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Heures d\'Ouverture',
    'contact.info.hoursWeekday': 'Lundi à Vendredi : 8h à 18h',
    'contact.info.hoursWeekend': 'Samedi et Dimanche : 8h à 20h',
    'contact.whatsapp': 'Discuter sur WhatsApp',
    'contact.whatsapp.message': 'Bonjour ! Je voudrais faire une réservation à Casa Tiana.',
    'contact.quickHelp': 'Besoin d\'Aide Rapide ?',
    'contact.urgent.title': 'Réservations Urgentes',
    'contact.urgent.desc': 'Pour les réservations de dernière minute',
    'contact.urgent.button': 'Appeler Maintenant',
    'contact.support.title': 'Support 24h',
    'contact.support.desc': 'Support via WhatsApp',
    'contact.support.button': 'Envoyer un Message',
    'contact.events.title': 'Événements Spéciaux',
    'contact.events.desc': 'Mariages et célébrations',
    'contact.events.button': 'Demander un Devis',
    
    // Footer
    'footer.description': 'Une expérience d\'hébergement unique en harmonie avec la nature. Située à Mindelo, nous offrons des moments inoubliables dans un environnement chaleureux et accueillant.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.followUs': 'Suivez-Nous',
    'footer.languages': 'Langues',
    'footer.awards': 'Distinctions',
    'footer.copyright': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.cancellation': 'Politique d\'Annulation',
    'footer.reviews': 'avis',
    
    // Blog (basic)
    'blog.back': 'Retour au Blog',
    'blog.category': 'Tourisme',
    'blog.author': 'Équipe Casa Tiana',
    'blog.reading': '8 min de lecture',
    'blog.readMore': 'Lire la suite',
    
    // 404
    'notfound.title': '404',
    'notfound.subtitle': 'Oups ! Page non trouvée',
    'notfound.home': 'Retour à l\'Accueil',
    
    // My Reservations
    'reservations.title': 'Mes Réservations',
    'reservations.empty': 'Vous n\'avez pas encore de réservation.',
    'reservations.viewRooms': 'Voir les Chambres Disponibles',
    'reservations.number': 'Réservation',
    'reservations.room': 'Chambre',
    'reservations.checkIn': 'Arrivée',
    'reservations.checkOut': 'Départ',
    'reservations.guests': 'Hôtes',
    'reservations.total': 'Total',
    'reservations.status': 'Statut',
    'reservations.actions': 'Actions',
    'reservations.edit': 'Modifier',
    'reservations.cancel': 'Annuler',
    'reservations.status.pending': 'En attente',
    'reservations.status.confirmed': 'Confirmée',
    'reservations.status.cancelled': 'Annulée',
    

    // Weather
    'weather.title': 'Météo à Mindelo',
    'weather.now': 'Maintenant',
    
    // Travel Recommendations
    'travel.title': 'Recommandations de Voyage',
    'travel.subtitle': 'Découvrez des expériences personnalisées à Mindelo avec l\'aide de notre IA',
    'travel.interests': 'Vos Intérêts',
    'travel.interests.culture': 'Culture & Histoire',
    'travel.interests.nature': 'Nature & Plages',
    'travel.interests.gastronomy': 'Gastronomie',
    'travel.interests.music': 'Musique & Vie Nocturne',
    'travel.interests.adventure': 'Aventure & Sports',
    'travel.duration': 'Durée du Séjour',
    'travel.duration.1-2': '1-2 jours',
    'travel.duration.3-5': '3-5 jours',
    'travel.duration.week': '1 semaine+',
    'travel.style': 'Style de Voyage',
    'travel.style.relaxed': 'Détendu',
    'travel.style.balanced': 'Équilibré',
    'travel.style.intensive': 'Intensif',
    'travel.generate': 'Générer des Recommandations',
    'travel.generating': 'Génération...',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Créer un Compte',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le Mot de passe',
    'auth.name': 'Nom Complet',
    'auth.forgotPassword': 'Mot de passe oublié',
    'auth.noAccount': 'Vous n\'avez pas de compte ?',
    'auth.hasAccount': 'Vous avez déjà un compte ?',
    'auth.backToSite': 'Retour au site',
    'auth.loginSubtitle': 'Connectez-vous pour faire des réservations',
    'auth.registerSubtitle': 'Créez votre compte pour commencer',
    'auth.loginButton': 'Connexion',
    'auth.registerButton': 'Créer un compte',
    'auth.loggingIn': 'Connexion en cours...',
    'auth.registering': 'Création du compte...',
    'auth.invalidEmail': 'Email invalide',
    'auth.passwordMinLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.loginError': 'Erreur de connexion',
    'auth.invalidCredentials': 'Email ou mot de passe incorrect.',
    'auth.welcome': 'Bienvenue !',
    'auth.loginSuccess': 'Connexion réussie.',
    'auth.emailRegistered': 'Email déjà enregistré',
    'auth.emailRegisteredMessage': 'Cet email est déjà enregistré. Essayez de vous connecter.',
    'auth.registerError': 'Erreur lors de l\'inscription',
    'auth.accountCreated': 'Vérifiez votre email !',
    'auth.accountCreatedMessage': 'Nous avons envoyé un lien de confirmation à votre email. Veuillez cliquer sur le lien pour activer votre compte.',
    'auth.continueWithGoogle': 'Continuer avec Google',
    'auth.orContinueWith': 'ou continuez avec email',
    
    // Booking Modal
    'booking.title': 'Faire une Réservation',
    'booking.confirmed': 'Réservation Confirmée !',
    'booking.loginRequired': 'Connectez-vous pour réserver',
    'booking.loginMessage': 'Pour faire une réservation, vous devez être connecté à votre compte.',
    'booking.loginButton': 'Se connecter',
    'booking.noAccount': 'Pas de compte ?',
    'booking.createAccount': 'Créer un compte gratuit',
    'booking.loginToContinue': 'Connectez-vous pour finaliser la réservation',
    'booking.loginToContinueDescription': 'Vos détails de réservation seront conservés après connexion.',
    'booking.step1Title': 'Sélectionnez les dates et le nombre d\'hôtes',
    'booking.checkIn': 'Arrivée',
    'booking.checkOut': 'Départ',
    'booking.selectCheckIn': 'Sélectionner l\'arrivée',
    'booking.selectCheckOut': 'Sélectionner le départ',
    'booking.guests': 'Nombre d\'hôtes',
    'booking.person': 'personne',
    'booking.people': 'personnes',
    'booking.next': 'Suivant',
    'booking.back': 'Retour',
    'booking.step2Title': 'Choisissez votre chambre',
    'booking.perNight': 'par nuit',
    'booking.summary': 'Résumé de la Réservation',
    'booking.period': 'Période',
    'booking.night': 'nuit',
    'booking.nights': 'nuits',
    'booking.collapse': 'Réduire',
    'booking.total': 'Total',
    'booking.step3Title': 'Informations sur l\'hôte',
    'booking.fullName': 'Nom complet *',
    'booking.fullNamePlaceholder': 'Votre nom complet',
    'booking.email': 'Email *',
    'booking.emailPlaceholder': 'votre@email.com',
    'booking.phone': 'Téléphone *',
    'booking.phonePlaceholder': '+33 1 23 45 67 89',
    'booking.specialRequests': 'Demandes spéciales',
    'booking.specialRequestsPlaceholder': 'Des demandes spéciales ? (facultatif)',
    'booking.finalSummary': 'Résumé Final',
    'booking.room': 'Chambre',
    'booking.processing': 'Traitement...',
    'booking.confirm': 'Confirmer la Réservation',
    'booking.confirmationTitle': 'Réservation Confirmée !',
    'booking.confirmationMessage': 'Votre réservation a été traitée avec succès. Vous recevrez un email de confirmation sous peu.',
    'booking.reservationNumber': 'Numéro de Réservation',
    'booking.keepNumber': 'Conservez ce numéro pour référence future',
    'booking.confirmationSentTo': 'Confirmation envoyée à',
    'booking.checkInAfter': 'après 14h',
    'booking.checkOutBefore': 'avant 12h',
    'booking.errorSelectRoom': 'Veuillez sélectionner une chambre.',
    'booking.errorTitle': 'Erreur',
    'booking.reservationConfirmed': 'Réservation Confirmée !',
    'booking.reservationConfirmedMessage': 'Email de confirmation envoyé.',
    'booking.reservationError': 'Erreur lors de la création de la réservation',
    'booking.reservationErrorMessage': 'Veuillez réessayer plus tard.',
    'booking.dateConflict': 'Les dates sélectionnées incluent des jours indisponibles. Veuillez choisir d\'autres dates.',
    'booking.reservationCreated': 'Réservation créée ! Choisissez comment vous souhaitez payer.',
    'booking.choosePayment': 'Choisissez comment vous souhaitez payer',
    'booking.payNow': 'Payer Maintenant',
    'booking.payLater': 'Payer Plus Tard',
    'booking.paymentSecure': 'Paiement sécurisé traité par SISP',
    'booking.errorSelectDates': 'Sélectionnez les dates d\'arrivée et de départ',
    'booking.errorFillFields': 'Remplissez tous les champs obligatoires',
    
    // WhatsApp Floating
    'whatsapp.floating.tooltip': 'Besoin d\'aide? Parlez-nous!',
    'whatsapp.floating.message': 'Bonjour! J\'ai une question sur Casa Tiana...',
    
    // Blog
    'blog.title': 'Blog & Conseils de Voyage',
    'blog.subtitle': 'Découvrez les secrets de la région, les événements locaux et des conseils exclusifs pour votre séjour',
    'blog.connectingWP': 'Connexion à WordPress... Affichage du contenu local.',
    'blog.newsletter.title': 'Recevez Nos Conseils par Email',
    'blog.newsletter.subtitle': 'Abonnez-vous à notre newsletter et soyez le premier informé des nouveaux itinéraires, événements spéciaux et offres exclusives pour les clients de Casa Tiana.',
    'blog.newsletter.placeholder': 'Votre meilleur email',
    'blog.newsletter.button': 'S\'abonner',
    'blog.newsletter.disclaimer': 'Nous promettons de ne pas envoyer de spam. Vous pouvez vous désabonner à tout moment.',
    
    // Events/WordPress Events
    'events.difficulty.easy': 'Facile',
    'events.difficulty.medium': 'Moyen',
    'events.difficulty.hard': 'Difficile',
    'events.at': 'à',
    'events.maxParticipants': 'Max. {0} participants',
    'events.includes': 'Comprend :',
    'events.moreItems': '+{0} autres éléments',
    'events.bookFor': 'Réserver - €{0}',
    'events.tripAdvisor': 'Plus de 150 avis 5 étoiles • 📍 TripAdvisor Travellers\' Choice 2023',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
